name: Docker Swarm Ingress CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - v*
    paths:
    - 'nginx-ingress/**'

env:
  IMAGE_NAME: docker-swarm-ingress
  NGINX_VERSION: 1.24.0-alpine

jobs:

  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker-compose -f .docker-compose.yml-ci build --pull --no-cache
    - name: Bringup the environment
      run: docker-compose -f .docker-compose.yml-ci up -d
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: List all containers
      run: docker ps -a
    - name: Testing connection to nginx
      run: docker-compose -f .docker-compose.yml-ci exec -T nginx curl --retry 10 --retry-connrefused -I http://localhost
    - uses: anchore/scan-action@v3
      id: scan
      with:
        image: "docker-swarm-ingress:latest"
        fail-build: false
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    - name: Inspect action SARIF report
      run: cat ${{ steps.scan.outputs.sarif }}
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
        IMAGE_ID_TAG=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$NGINX_VERSION
        echo IMAGE_ID=$IMAGE_ID
        echo IMAGE_ID_TAG=$IMAGE_ID_TAG
        docker tag $IMAGE_NAME:latest $IMAGE_ID
        docker tag $IMAGE_NAME:latest $IMAGE_ID_TAG
        docker push $IMAGE_ID
        docker push $IMAGE_ID_TAG