name: Docker Swarm Ingress

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  DOCKER_SWARM_INGRESS_FULL_IMAGE: garutilorenzo/docker-swarm-ingress:localbuild

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: docker-compose -f .docker-compose.yml-ci build --pull --no-cache
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          DOCKER_SWARM_INGRESS_IMAGE_NAME=${DOCKER_SWARM_INGRESS_FULL_IMAGE#*/}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$DOCKER_SWARM_INGRESS_IMAGE_NAME:latest
          echo DOCKER_SWARM_INGRESS_IMAGE_NAME=$DOCKER_SWARM_INGRESS_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $DOCKER_SWARM_INGRESS_FULL_IMAGE $IMAGE_ID
          docker push $IMAGE_ID