name: Docker Swarm Ingress Packages

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  COMPOSE_IMAGE_NAME: garutilorenzo/docker-swarm-ingress
  COMPOSE_IMAGE_TAG: localbuild

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: docker-compose -f .docker-compose.yml-ci build --pull --no-cache
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          DOCKER_SWARM_INGRESS_FULL_IMAGE=$COMPOSE_IMAGE_NAME:$COMPOSE_IMAGE_TAG
          DOCKER_SWARM_INGRESS_IMAGE_NAME=${COMPOSE_IMAGE_NAME#*/}:latest
          echo DOCKER_SWARM_INGRESS_IMAGE_NAME=$DOCKER_SWARM_INGRESS_IMAGE_NAME
          echo DOCKER_SWARM_INGRESS_FULL_IMAGE=$DOCKER_SWARM_INGRESS_FULL_IMAGE
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$COMPOSE_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $DOCKER_SWARM_INGRESS_FULL_IMAGE $IMAGE_ID
          docker push $IMAGE_ID